// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPkYlyo6wGVJysRH6OyyUUzjKVRtfWdwA',
    appId: '1:767962042559:web:252d71183c0d67f547f60a',
    messagingSenderId: '767962042559',
    projectId: 'ecotrails-4386c',
    authDomain: 'ecotrails-4386c.firebaseapp.com',
    storageBucket: 'ecotrails-4386c.firebasestorage.app',
    measurementId: 'G-E4LK3R1552',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBhgvTNJsQleRbjbTwd9D2Y4eb7BM4F4',
    appId: '1:767962042559:android:60a8e94f807fa16347f60a',
    messagingSenderId: '767962042559',
    projectId: 'ecotrails-4386c',
    storageBucket: 'ecotrails-4386c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNQvN5RJgMUtXj0n0S2dGGWrAIOY-oKI',
    appId: '1:767962042559:ios:f8b99a6f6ff28dc547f60a',
    messagingSenderId: '767962042559',
    projectId: 'ecotrails-4386c',
    storageBucket: 'ecotrails-4386c.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNQvN5RJgMUtXj0n0S2dGGWrAIOY-oKI',
    appId: '1:767962042559:ios:f8b99a6f6ff28dc547f60a',
    messagingSenderId: '767962042559',
    projectId: 'ecotrails-4386c',
    storageBucket: 'ecotrails-4386c.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPkYlyo6wGVJysRH6OyyUUzjKVRtfWdwA',
    appId: '1:767962042559:web:34548e62caaa7c0747f60a',
    messagingSenderId: '767962042559',
    projectId: 'ecotrails-4386c',
    authDomain: 'ecotrails-4386c.firebaseapp.com',
    storageBucket: 'ecotrails-4386c.firebasestorage.app',
    measurementId: 'G-HLXGDG6WBE',
  );

}